name: Tests

on: [push, pull_request]

jobs:
  tests-ubuntu:
    runs-on: ubuntu-latest
    env:
      BROWSERS: preset:local
      CONCURRENT_BROWSERS: 3

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2

      - name: Install playwright deps
        run: npx playwright install-deps

      - name: NPM install
        run: npm ci

      - name: Lerna bootstrap
        run: npm run bootstrap

      - name: Build
        run: npm run build

      - name: Test
        run: npm run test