name: Tests

on: [push, pull_request]

jobs:
  tests-local:
    runs-on: windows-latest

    defaults:
      run:
          shell: wsl-bash {0}

    steps:
      - uses: actions/checkout@v2
      - uses: Vampire/setup-wsl@v1
      - uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: 'npm'
          cache-dependency-path: '**/package-lock.json'

      
      - name: Install playwright deps
        run: npx playwright install-deps

      - name: NPM install
        run: npm ci

      - name: Lerna bootstrap
        run: npm run bootstrap

      - name: Build
        run: npm run build

      # - name: Test
      #   env:
      #     BROWSERS: preset:local
      #     CONCURRENT_BROWSERS: 3
      #   run: wsl npm run test
